add onboarding setup
AmpersandTarski/prototype-frontend pull request #111
Opened 2022-12-20 12:35 UTC by LiWeiYeh

2022-12-20 12:41 UTC, PatrickR079 reviewed
This is as good as the same as the current README file. I suggest you convert the current README file to this

2022-12-20 12:44 UTC, PatrickR079 requested changes

2022-12-20 12:44 UTC, PatrickR079 commented on docs/onboarding.md
> +5. Inside the **project-administration** folder, run the docker command `docker compose up -d`. This installs the environment into **Docker Desktop**.
I miss the step where you fill the database with content

2022-12-22 11:55 UTC, PatrickR079 approved these changes

2022-12-23 07:57 UTC, AndreOrdina approved these changes

2022-12-23 07:57 UTC, merged