Feat/admin import population page
AmpersandTarski/prototype-frontend pull request #173
Opened 2023-02-14 14:32 UTC by byTinus

User can upload files through the dropzone. Aside from the F12 window, there is no confirm/error response message yet. This can be added once #166 has been implemented.

2023-02-14 15:46 UTC, LiWeiYeh commented on src/app/admin/population/import/import.component.html
> +<!--
Is this TODO still relevant? If not, it should be deleted.

2023-02-14 15:47 UTC, LiWeiYeh commented on src/app/admin/population/import/import.component.html
> +                    *ngFor="let f of files"
I would recommend renaming this to `let file of files`. This is more readable when you look at the code below that will read it like: `{{ file.name }}` and `{{ file.type }}`.

2023-02-14 15:49 UTC, LiWeiYeh commented on src/app/admin/population/import/import.component.ts
> +    console.log(event);
Remove the console.log

2023-02-14 15:50 UTC, LiWeiYeh commented on src/app/admin/population/import/import.component.ts
> +    console.log(event);
Remove the console.log

2023-02-14 15:51 UTC, LiWeiYeh commented on src/app/admin/population/import/import.component.ts
> +  onSelect(event: { addedFiles: any }) {
isn't addedFiles of type `File`? Unless there is no corresponding type to addedFiles, `unknown` is preferred over `any`. The aim is to have as few `any`s as possible.

2023-02-14 15:58 UTC, LiWeiYeh commented on src/app/admin/population/import/import.component.ts
> +    let response = this.populationService.importPopulation(this.files);
The `response.subscribe(...)` on line 49 is unnecessary. What should happen is to call the `subscribe` method such that the `populationService`'s method is called which requires the `subscribe` method. It would also be nice to show the user that the upload has been successful. You can check within the file `src\app\admin\population\population.component.ts`, the method `exportPopulation()` and create something similar.

2023-02-14 16:16 UTC, LiWeiYeh commented on src/app/admin/population/population.service.ts
> +    console.log('importPopulation() called with files: ');
console.log is for developer's debug purposes and should not belong in code in dev/production (except for specific cases).

2023-02-14 16:16 UTC, LiWeiYeh commented on src/app/admin/population/population.service.ts
> +      console.log(file.name);
console.log

2023-02-14 16:16 UTC, LiWeiYeh commented on src/app/admin/population/population.service.ts
> +    return this.http.post(this.importUrl, formData);
It's best practice to also pass the type of the `http.post` with `<>`,see line 13 for example.

2023-02-14 16:18 UTC, LiWeiYeh requested changes
Resolve comments first please.

2023-02-15 07:50 UTC, AndreOrdina submitted a review, later dismissed

2023-02-15 09:13 UTC, LiWeiYeh requested changes

2023-02-15 14:13 UTC, byTinus commented on src/app/admin/population/import/import.component.ts
> +      this.populationService.importPopulation(this.files.pop()).subscribe({
When I was applying your suggestions yesterday I found an issue where the upload all feature was broken, so I changed it into this while loop, which came with its own bugs. 
There's an easier way where it simply uploads all the files, but then there's no good way of notifying the user about the status of the files; they just disappear. I think for now that's the best option, and once we have #166 , we can add notifications here too.
Tomorrow I will push this change, if you agree.

2023-02-15 14:46 UTC, LiWeiYeh commented on src/app/admin/population/import/import.component.ts
> +      this.populationService.importPopulation(this.files.pop()).subscribe({
Fine by me. If you resolve the other comments I will give an approve. We can discuss this with the POs next monday.

2023-02-17 09:54 UTC, LiWeiYeh approved these changes

2023-02-20 23:50 UTC, AndreOrdina approved these changes

2023-02-21 12:53 UTC, LiWeiYeh approved these changes

2023-02-22 08:23 UTC, AndreOrdina approved these changes

2023-02-22 08:23 UTC, merged