Feat/add dynamic nav menu
AmpersandTarski/prototype-frontend pull request #192
Opened 2023-02-28 17:28 UTC by byTinus

This branch adds the dynamic nav menu. With dynamic, we mean that the menu items are fetched from the backend, instead of being hardcoded. 

Some design choices / behaviour:
 - While submenus are currently not showing (because of the given data), they are supported. Main 'parent' items don't show their submenus in a dropdown, but if one of those submenus has submenus, a dropdown arrow will appear.
 - When an item with a parent is read, but the parent does not exist yet, it is put in a temporary `childItems()` array. Once the rest of the items have been added, the 'parked' child items are added. 

(Potentially) unwanted behaviour:
 - GET navbar is called twice. 
 - This happens each time a new page is loaded (i.e. it is not cached)
 - If any MenuItem has a parent assigned that does not exist, the while loop will not terminate.

2023-03-01 09:27 UTC, LiWeiYeh commented on src/app/layout/app.menu.component.ts
> +        var menuItem: MenuItem;
use `let` instead of `var`. `let` keeps the variable within it's designated code block, whilst var makes it sort of global (which is almost never wanted). Always consider using let over var.

2023-03-01 09:52 UTC, LiWeiYeh commented on src/app/layout/app.menu.component.ts
> +        if (nav.ifc == null) {
This has a lot of `if-then-else` statements nested within each other. Let's try to find a way to clean this up a bit.

2023-03-01 09:54 UTC, LiWeiYeh commented on src/app/layout/app.menu.component.ts
> +            let parentItem = this.model.find((item) => item.id == nav.parent);
It looks like nothing is happening to the parentItem, is this intended?

2023-03-01 09:55 UTC, LiWeiYeh commented on src/app/layout/app.menu.component.ts
> +    let childItems = new Array<MenuItem>(); // Storage for child items where parent is not added yet.
It looks like nothing is happening with the childItems, is this intended?

2023-03-01 09:57 UTC, LiWeiYeh commented on src/app/layout/app.menu.component.ts
> +  fetchMenuItems() {
`fetch` sounds like you're **getting** something. Maybe change this to `addMenuItems()`, or make this function return the MenuItems as a list, and then apply the forEach just like the `adminMenuItems`

2023-03-01 09:57 UTC, LiWeiYeh commented on src/app/layout/app.menu.service.ts
> +import { MenuItem } from 'primeng/api/menuitem';
remove unnecessary imports

2023-03-01 10:04 UTC, LiWeiYeh commented on src/app/project-administration/project-administration.module.ts
> +export const menuItems: MenuItem[] = [];
I'd argue that the logic for the creation of the menuItems which is currently done in `app.menu.component.ts` should be done here, but then again, that might be ugly :x

2023-03-01 10:07 UTC, LiWeiYeh requested changes
The loading bit is quite annoying, let's discuss this with michiel or find a way to stop it from calling every time.

2023-03-02 10:40 UTC, AndreOrdina approved these changes

2023-03-02 10:42 UTC, AndreOrdina commented
> The loading bit is quite annoying, let's discuss this with michiel or find a way to stop it from calling every time.

The rest seems fine apart from this point indeed.

2023-03-02 10:53 UTC, LiWeiYeh commented on src/app/layout/app.menu.component.ts
> +  addPrototypeItems() {
make private

2023-03-02 10:53 UTC, LiWeiYeh commented on src/app/layout/app.menu.component.ts
> +  addMenuItems() {
make private

2023-03-02 11:00 UTC, LiWeiYeh approved these changes

2023-03-02 16:00 UTC, merged