Cache navbar items
AmpersandTarski/prototype-frontend pull request #207
Opened 2023-03-14 14:48 UTC by byTinus

A `navbar` request is needed to receive menu items. Previously, this was done twice per page reload: once for the top bar, and once for the main menu. With this change, the menu items are stored in session storage. Now, the API is only called with a new session, i.e. a new tab.

2023-03-14 15:34 UTC, LiWeiYeh commented on src/app/admin/roles/roles.component.ts
> +    let menuCache = sessionStorage.getItem('roleMenuItems');
Nice solution! I think however this fits better in the `roles.service.ts` file rather than this file. Using that way, we can keep the `ngOnInit()` function still pretty clean without doing too much login in there, which is actually preprocessed in the `this.rolesService.getRoles()` function.

2023-03-14 15:40 UTC, LiWeiYeh commented on src/app/admin/roles/roles.component.ts
> +    let menuCache = sessionStorage.getItem('roleMenuItems');
I would also argue that menuCache seems pretty vague, as in, it is not very clear what menuCache this is for. Perhaps just call this rolesMenu? I have removed the word cache, since I think you shouldn't have to know it retrieves the information as a cache under the hood.

2023-03-14 15:46 UTC, LiWeiYeh commented on src/app/layout/app.menu.component.ts
> +    let navbarCache = sessionStorage.getItem('menuItems');
I would argue that these 11 lines should be placed in another private function in this file. Check if you agree on this, if not, let's discuss.

2023-03-14 15:48 UTC, LiWeiYeh requested changes
Resolve comments first!

2023-03-14 16:03 UTC, byTinus commented on src/app/admin/roles/roles.component.ts
> +    let menuCache = sessionStorage.getItem('roleMenuItems');
I agree. I will move/refactor some elements to make it cleaner

2023-03-22 12:17 UTC, LiWeiYeh approved these changes

2023-03-22 12:19 UTC, merged