Documentation for the atomic components
AmpersandTarski/prototype-frontend pull request #77
Opened 2022-11-30 21:58 UTC by MarkCorazon

Its been discussed with Han to make this into a folder named docs, and made available into one file.
Please check this for any spelling or overall mistakes please.

2022-12-01 09:27 UTC, PatrickR079 submitted a review, later dismissed

2022-12-01 09:31 UTC, hanjoosten requested changes
Nice work @MarkCorazon! I have some really minor change requests.

2022-12-01 09:31 UTC, hanjoosten commented on docs/documentation.md
> +REPRESENT projectActive TYPE BOOLEAN
In Ampersand, the name of Concept needs to start with an uppercase letter. Please fix this in all examples, so the reader isn't confused.

2022-12-01 09:31 UTC, hanjoosten commented on docs/documentation.md
> +With the ampersand project, its possible to create a variety of input fields and ways to display those input fields or simply data.
The name of the file `documentation.md` is very general. Please make it more specific to the content you are describing. maybe something like `interface-components.md`

2022-12-02 07:55 UTC, MarkCorazon commented on docs/documentation.md
> +With the ampersand project, its possible to create a variety of input fields and ways to display those input fields or simply data.
Thats a good point. 23:00 was not my brightest moment i guess.

2022-12-02 07:56 UTC, MarkCorazon commented on docs/documentation.md
> +REPRESENT projectActive TYPE BOOLEAN
Check, this is now changed to start with an uppercase

2022-12-02 14:30 UTC, PatrickR079 approved these changes

2022-12-02 14:31 UTC, LiWeiYeh approved these changes

2022-12-02 14:38 UTC, merged