Feature/inactive projects view dev
AmpersandTarski/prototype-frontend pull request #97
Opened 2022-12-08 15:49 UTC by DirkSuelmann

2022-12-08 16:11 UTC, LiWeiYeh approved these changes
Congrats on your first PR! It looks good! It seems like the editing functionality has not been implemented yet in this PR though. I approve this PR, but be sure to handle edit functionality before you set your work item on "done".

2022-12-08 16:13 UTC, LiWeiYeh requested changes
Whoops, my previous PR went through so there are some merge conflics. Resolve them first!

2022-12-09 09:28 UTC, PatrickR079 requested changes

2022-12-09 09:28 UTC, PatrickR079 commented on src/app/project-administration/inactive-projects/inactive-projects.interface.ts
> +export interface InactiveProjectsInterface extends ObjectBase {
You can use the 'active-projects' interface for this. My request when you apply this change: can you rename the 'active-projects' interface to 'projects' interface?

2022-12-09 10:34 UTC, DirkSuelmann commented on src/app/project-administration/inactive-projects/inactive-projects.interface.ts
> +export interface InactiveProjectsInterface extends ObjectBase {
You would think that the data would be the same, but it is slightly different. So i've added a ``ProjectsInterface`` as a base, and made the ``ActiveProjectsInterface`` extend this interface.

2022-12-20 08:51 UTC, LiWeiYeh commented on src/app/project-administration/backend.mock.service.ts
> +import { ProjectsInterface } from './projects.interface';
Should be InactiveProjectsInterface

2022-12-20 08:51 UTC, LiWeiYeh commented on src/app/project-administration/backend.mock.service.ts
> +  getInactiveProjects(): Observable<ProjectsInterface[]> {
Should be of type InactiveProjectsInterface

2022-12-20 08:52 UTC, LiWeiYeh commented on src/app/project-administration/backend.service.interface.ts
> +import { ProjectsInterface } from './projects.interface';
InactiveProjectsInterface

2022-12-20 08:53 UTC, LiWeiYeh commented on src/app/project-administration/backend.service.ts
> +import { ProjectsInterface } from './projects.interface';
InactiveProjectsInterface

2022-12-20 08:53 UTC, LiWeiYeh commented on src/app/project-administration/backend.service.ts
> +import { ProjectInterface } from './project/project.interface';
InactiveProjectsInterface

2022-12-20 08:53 UTC, LiWeiYeh commented on src/app/project-administration/backend.service.ts
> +  public getInactiveProjects(): Observable<ProjectsInterface[]> {
InactiveProjectsInterface

2022-12-20 08:55 UTC, LiWeiYeh requested changes
Apply the change you made in your last commit, which is changing the ProjectInterface into InactiveProjecstInterface and ActiveProjectsInterface, The change of InactiveProjectsInterface has not been applied to other files, e.g. backend.services

2022-12-20 09:10 UTC, LiWeiYeh commented on src/app/project-administration/backend.service.ts
> +import { ProjectInterface } from './project/project.interface';
Is supposed to be for the Project

2022-12-20 09:10 UTC, LiWeiYeh approved these changes

2022-12-20 09:12 UTC, PatrickR079 approved these changes

2022-12-20 09:12 UTC, merged